version: '3.1'
services:
  web:
    image: homesumana/odoo-docker:15
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo15-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ../odoo-addons:/mnt/extra-addons
    environment:
      - TZ=Asia/Bangkok
    restart: unless-stopped
    container_name: odoo15-homesumana-web
    command:
      -- --init base_setup
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - odoo15-db-data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Bangkok
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    restart: unless-stopped
    container_name: odoo15-homesumana-db
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Bangkok
    restart: unless-stopped
    container_name: odoo15-homesumana-adminer
  vpn:
    image: ngrok/ngrok
    depends_on:
      - web
    ports:
      - "4040:4040"
    environment:
      - TZ=Asia/Bangkok
      - NGROK_AUTHTOKEN=22JnrlocwQGRIFARXyhHR1tn5jA_bfXJZHuzSZVtdfCE3mq2
    restart: unless-stopped
    container_name: odoo15-homesumana-ngrok
    command:
      http odoo15-homesumana-web:8069
volumes:
  odoo15-web-data:
  odoo15-db-data:
